import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from "next/font/local";
import Container from "@/components/layouts/Container";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const banglaFont = localFont({
  src: "../fonts/mayaboti-normal.ttf",
});

export const metadata = {
  title: {
    default: "Hero Kidz",
    template: `%s | Hero Kidz`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header>
          <Navbar />
        </header>
        <Container className="py-2 min-h-[calc(100vh-302px)]">
          {children}
        </Container>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
