import Products from "@/components/home/Products";
import React from "react";

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const page = () => {
  return <Products />;
};

export default page;
